import StyleDictionary from "style-dictionary";
import { readFileSync, mkdirSync, writeFileSync, existsSync } from "fs";
import { dirname, join } from "path";

const ROOT = process.cwd();
const TOKENS_FILE = join(ROOT, "tokens", "harmony-tokens.json");

const raw = JSON.parse(readFileSync(TOKENS_FILE, "utf-8"));

function flattenColors(obj, mode) {
  const result = {};
  function extractLeaf(val, path) {
    if (val.value !== undefined && val.type === "color") {
      const name = path.join("_");
      result[name] = val.value;
      return;
    }
    for (const [k, v] of Object.entries(val)) {
      if (v && typeof v === "object") {
        if (v.value !== undefined && v.type === "color") {
          result[[...path, k].join("_")] = v.value;
        } else if (v.value !== undefined && v.type !== "color") {
          // skip non-color tokens
        } else {
          extractLeaf(v, [...path, k]);
        }
      }
    }
  }
  function walkTop(node, path) {
    for (const [key, val] of Object.entries(node)) {
      if (val && typeof val === "object") {
        if (key === mode) {
          if (val.value !== undefined) {
            result[path.join("_")] = val.value;
          } else {
            extractLeaf(val, path);
          }
        } else if (val.value === undefined) {
          walkTop(val, [...path, key]);
        }
      }
    }
  }
  walkTop(obj, []);
  return result;
}

function flattenNumbers(obj, basePath, typeFilter, unit) {
  const result = {};
  function walk(node, path) {
    for (const [key, val] of Object.entries(node)) {
      if (val && typeof val === "object") {
        if (val.value !== undefined && val.type === typeFilter) {
          const name = [...path, key].join("_");
          result[name] = unit ? `${val.value}${unit}` : val.value;
        } else if (val.value !== undefined && val.type === "dimension") {
          const name = [...path, key].join("_");
          result[name] = `${val.value}${val.unit || "vp"}`;
        } else {
          walk(val, [...path, key]);
        }
      }
    }
  }
  walk(obj, []);
  return result;
}

const lightColors = flattenColors(raw, "light");
const darkColors = flattenColors(raw, "dark");

const lightColorEntries = Object.entries(lightColors);
const darkColorEntries = Object.entries(darkColors);

function hexToArgb(hex) {
  const h = hex.replace("#", "");
  const r = parseInt(h.substring(0, 2), 16);
  const g = parseInt(h.substring(2, 4), 16);
  const b = parseInt(h.substring(4, 6), 16);
  return `#FF${h.toUpperCase()}`;
}

function nameToAndroidResource(name) {
  return "harmony_" + name.toLowerCase();
}

const androidColors = lightColorEntries
  .map(([name, hex]) => `    <color name="${nameToAndroidResource(name)}">${hexToArgb(hex)}</color>`)
  .join("\n");

const androidColorsNight = darkColorEntries
  .map(([name, hex]) => `    <color name="${nameToAndroidResource(name)}">${hexToArgb(hex)}</color>`)
  .join("\n");

function collectDimensions(node, path = []) {
  const result = {};
  for (const [key, val] of Object.entries(node)) {
    if (val && typeof val === "object") {
      if (val.value !== undefined && val.type === "dimension") {
        const name = [...path, key].join("_");
        result[name] = `${val.value}${val.unit || "vp"}`;
      } else {
        Object.assign(result, collectDimensions(val, [...path, key]));
      }
    }
  }
  return result;
}

const fontSizes = {};
for (const [name, data] of Object.entries(raw.font)) {
  if (data.size && data.size.type === "dimension") {
    fontSizes[`font_${name}_size`] = `${data.size.value}${data.size.unit || "fp"}`;
  }
}

const spacing = collectDimensions(raw.space, ["space"]);
const radius = collectDimensions(raw.radius, ["radius"]);
const motion = collectDimensions(raw.motion, ["motion"]);
const allDimensions = { ...fontSizes, ...spacing, ...radius, ...motion };

const androidDimens = Object.entries(allDimensions)
  .map(([name, val]) => {
    if (val.endsWith("vp")) {
      return `    <dimen name="${nameToAndroidResource(name)}">${val}</dimen>`;
    } else if (val.endsWith("fp")) {
      return `    <dimen name="${nameToAndroidResource(name)}">${val}</dimen>`;
    } else {
      return `    <item name="${nameToAndroidResource(name)}" type="${val.includes(".") ? "string" : "integer"}">${val}</item>`;
    }
  })
  .join("\n");

const ANDROID_RES_DIR = join(ROOT, "platforms", "android", "src", "main", "res");

const lightColorsXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by Style Dictionary from tokens/harmony-tokens.json -->
<!-- DO NOT EDIT MANUALLY — modify tokens and run: npm run build:tokens -->
<resources>
${androidColors}
</resources>
`;

const darkColorsXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by Style Dictionary from tokens/harmony-tokens.json -->
<!-- DO NOT EDIT MANUALLY — modify tokens and run: npm run build:tokens -->
<resources>
${androidColorsNight}
</resources>
`;

const dimensXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by Style Dictionary from tokens/harmony-tokens.json -->
<!-- DO NOT EDIT MANUALLY — modify tokens and run: npm run build:tokens -->
<resources>
${androidDimens}
</resources>
`;

const valuesDir = join(ANDROID_RES_DIR, "values");
const valuesNightDir = join(ANDROID_RES_DIR, "values-night");
mkdirSync(valuesDir, { recursive: true });
mkdirSync(valuesNightDir, { recursive: true });

writeFileSync(join(valuesDir, "harmony_colors.xml"), lightColorsXml);
writeFileSync(join(valuesNightDir, "harmony_colors.xml"), darkColorsXml);
writeFileSync(join(valuesDir, "harmony_dimens.xml"), dimensXml);

const colorKeys = Object.keys(lightColors);
const harmonyColorJson = {
  "color": [
    ...colorKeys.map(name => ({
      "name": name,
      "value": lightColors[name]
    }))
  ]
};

const darkColorKeys = Object.keys(darkColors);
const harmonyDarkColorJson = {
  "color": [
    ...darkColorKeys.map(name => ({
      "name": name,
      "value": darkColors[name]
    }))
  ]
};

const floatEntries = Object.entries(allDimensions).filter(([_, v]) => v.match(/^\d/));
const harmonyFloatJson = {
  "float": [
    ...floatEntries.map(([name, val]) => ({
      "name": name,
      "value": parseFloat(val.replace(/[a-z]+$/, ""))
    }))
  ]
};

const HARMONY_RES_DIR = join(ROOT, "platforms", "harmony", "AppScope", "resources");
const baseElementDir = join(HARMONY_RES_DIR, "base", "element");
const darkElementDir = join(HARMONY_RES_DIR, "dark", "element");
mkdirSync(baseElementDir, { recursive: true });
mkdirSync(darkElementDir, { recursive: true });

writeFileSync(join(baseElementDir, "color.json"), JSON.stringify(harmonyColorJson, null, 2) + "\n");
writeFileSync(join(darkElementDir, "color.json"), JSON.stringify(harmonyDarkColorJson, null, 2) + "\n");
writeFileSync(join(baseElementDir, "float.json"), JSON.stringify(harmonyFloatJson, null, 2) + "\n");

const composeDir = join(ROOT, "platforms", "android", "src", "main", "java", "com", "amap", "agenui", "platform", "harmony", "tokens");
mkdirSync(composeDir, { recursive: true });

const composeColors = lightColorEntries
  .map(([name, hex]) => {
    const h = hex.replace("#", "");
    return `    val ${name}: Color = Color(0xFF${h.toUpperCase()})`;
  })
  .join("\n");

const composeDarkColors = darkColorEntries
  .map(([name, hex]) => {
    const h = hex.replace("#", "");
    return `    val ${name}: Color = Color(0xFF${h.toUpperCase()})`;
  })
  .join("\n");

const composeDimens = Object.entries(allDimensions)
  .map(([name, val]) => {
    const num = val.replace(/[a-z]+$/, "");
    if (val.endsWith("vp")) {
      return `    val ${name}: Dp = ${num}.dp`;
    } else if (val.endsWith("fp")) {
      return `    val ${name}: TextUnit = ${num}.sp`;
    } else {
      return `    val ${name} = ${val}`;
    }
  })
  .join("\n");

const composeKt = `package com.amap.agenui.platform.harmony.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * Auto-generated from tokens/harmony-tokens.json.
 * DO NOT EDIT MANUALLY — modify tokens and run: npm run build:tokens
 */
object HarmonyColorTokens {
${composeColors}
}

object HarmonyDarkColorTokens {
${composeDarkColors}
}

object HarmonyDimenTokens {
${composeDimens}
}
`;

writeFileSync(join(composeDir, "HarmonyTokens.kt"), composeKt);

console.log("[tokens] Built successfully:");
console.log("  Android:");
console.log("    " + join(valuesDir, "harmony_colors.xml").replace(ROOT + "/", ""));
console.log("    " + join(valuesNightDir, "harmony_colors.xml").replace(ROOT + "/", ""));
console.log("    " + join(valuesDir, "harmony_dimens.xml").replace(ROOT + "/", ""));
console.log("  Compose:");
console.log("    " + join(composeDir, "HarmonyTokens.kt").replace(ROOT + "/", ""));
console.log("  HarmonyOS:");
console.log("    " + join(baseElementDir, "color.json").replace(ROOT + "/", ""));
console.log("    " + join(darkElementDir, "color.json").replace(ROOT + "/", ""));
console.log("    " + join(baseElementDir, "float.json").replace(ROOT + "/", ""));
console.log(`  Colors: ${colorKeys.length} light + ${darkColorKeys.length} dark`);
console.log(`  Dimensions: ${floatEntries.length}`);
