platform :ios, '13.0'

target 'Playground' do

  pod 'AGenUI', :path => '../../../platforms/ios/AGenUI_ForSDK.podspec'

  pod 'MarkdownKit'
  pod 'DGCharts'
  pod 'lottie-ios'

  target 'AGenUITests' do
    inherit! :search_paths
  end

end
