package com.amap.agenui.annotation;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;

/**
 * Collects all {@link BuiltInComponent}-annotated factory classes and generates
 * {@code BuiltInComponentRegistrar} with a {@code registerAll()} method that
 * registers each discovered component.
 */
@SupportedAnnotationTypes("com.amap.agenui.annotation.BuiltInComponent")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
public class BuiltInComponentProcessor extends AbstractProcessor {

    private static final String FACTORY_SUFFIX = "ComponentFactory";
    private static final String REGISTRAR_PACKAGE = "com.amap.agenui.render.component";
    private static final String REGISTRAR_CLASS = "BuiltInComponentRegistrar";
    private static final String FACTORY_PACKAGE = "com.amap.agenui.render.component.factory";

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }

        TypeElement annotationType = processingEnv.getElementUtils()
            .getTypeElement("com.amap.agenui.annotation.BuiltInComponent");
        if (annotationType == null) {
            return false;
        }
        Set<? extends Element> elements = roundEnv.getElementsAnnotatedWith(annotationType);
        if (elements.isEmpty()) {
            return false;
        }

        List<ComponentEntry> entries = new ArrayList<>();

        for (Element element : elements) {
            String className = element.getSimpleName().toString();
            if (!className.endsWith(FACTORY_SUFFIX)) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "@BuiltInComponent class name must end with '" + FACTORY_SUFFIX +
                    "', got: " + className, element);
                continue;
            }
            String componentName = className.substring(0, className.length() - FACTORY_SUFFIX.length());
            entries.add(new ComponentEntry(componentName, className));
        }

        entries.sort(Comparator.comparing(e -> e.componentName));

        try {
            generateRegistrar(entries);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                "Failed to generate " + REGISTRAR_CLASS + ": " + e.getMessage());
        }

        return true;
    }

    private void generateRegistrar(List<ComponentEntry> entries) throws IOException {
        JavaFileObject file = processingEnv.getFiler()
            .createSourceFile(REGISTRAR_PACKAGE + "." + REGISTRAR_CLASS);

        try (Writer writer = file.openWriter()) {
            writer.write("package " + REGISTRAR_PACKAGE + ";\n\n");

            for (ComponentEntry entry : entries) {
                writer.write("import " + FACTORY_PACKAGE + "." + entry.factoryClass + ";\n");
            }

            writer.write("\n");
            writer.write("/**\n");
            writer.write(" * Auto-generated by {@link " + getClass().getSimpleName() + "}.\n");
            writer.write(" * " + entries.size() + " components registered.\n");
            writer.write(" */\n");
            writer.write("public class " + REGISTRAR_CLASS + " {\n\n");
            writer.write("    private " + REGISTRAR_CLASS + "() {\n");
            writer.write("    }\n\n");
            writer.write("    public static void registerAll() {\n");

            for (ComponentEntry entry : entries) {
                writer.write("        ComponentRegistry.registerComponent(\"" +
                    entry.componentName + "\", new " + entry.factoryClass + "());\n");
            }

            writer.write("    }\n");
            writer.write("}\n");
        }
    }

    private static class ComponentEntry {
        final String componentName;
        final String factoryClass;

        ComponentEntry(String componentName, String factoryClass) {
            this.componentName = componentName;
            this.factoryClass = factoryClass;
        }
    }
}
